# Generated by Django 6.0.6 on 2026-08-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_solicitudcotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='notificacion_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada_smtp', 'Enviada por SMTP'), ('sin_configurar', 'Proveedor no configurado'), ('fallida', 'Fallida')], default='pendiente', editable=False, max_length=20, verbose_name='estado de notificación'),
        ),
    ]
